services:
  postgres:
    ports:
      - "5432:5432"

  redis:
    ports:
      - "6379:6379"

  worker-fast-1:
    profiles:
      - worker-vps

  worker-fast-2:
    profiles:
      - worker-vps

  worker-slow:
    profiles:
      - worker-vps
